image:
  file: .gitpod.Dockerfile

# Optionally, you can map ports (e.g., a web server) if you want to run a Clojure web app later.
# ports:
#   - port: 8080
#     onOpen: preview

tasks:
  - name: "Initialize environment"
    init: |
      # Just print Clojure version to verify the CLI is installed
      clojure --version

# Gitpod can automatically install VS Code extensions from OpenVSX
vscode:
  extensions:
    # Calva is "betterthantomorrow.calva" on OpenVSX
    - betterthantomorrow.calva
